### ISSUE TITLE
image_grid error

### ISSUE THREAD

**Issue by D1mon** [joshuabenuck/twitch#1]
error: failed to load source for a dependency on `image_grid`

**Comment by joshuabenuck** [comment]
The image_grid dependency is no longer needed. I ported the graphical launcher functionality to my [doorways](https://github.com/joshuabenuck/doorways) project. It still has a relative path for several of its dependencies and is in similar need of cleanup.

I updated the readme to reflect the current functionality and cleaned the utility up a bit so it isn't so finicky to run. Please give it a try and let me know if it works for you. You are the first person other than me to attempt to run it.
